# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Metricoscience.ui'
#
# Created: Tue May 15 22:44:58 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Metricoscience(object):
    def setupUi(self, Metricoscience):
        Metricoscience.setObjectName(_fromUtf8("Metricoscience"))
        Metricoscience.resize(851, 526)
        Metricoscience.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.centralwidget = QtGui.QWidget(Metricoscience)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 851, 101))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(52, 52, 52);\n"
"image: url(:/newPrefix/mos.qrc);\n"
"border-image: url(:/newPrefix/mos.qrc);\n"
""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalFrame = QtGui.QFrame(self.frame)
        self.horizontalFrame.setGeometry(QtCore.QRect(230, 40, 401, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.horizontalFrame.setPalette(palette)
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(52, 52, 52);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4, QtCore.Qt.AlignHCenter)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(52, 52, 52);"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(52, 52, 52);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2, QtCore.Qt.AlignHCenter)
        self.pushButton = QtGui.QPushButton(self.horizontalFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(52, 52, 52);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 100, 851, 20))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 120, 851, 281))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame_2 = QtGui.QFrame(self.frame_4)
        self.frame_2.setGeometry(QtCore.QRect(60, 40, 721, 231))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.radioButton = QtGui.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(50, 10, 141, 20))
        self.radioButton.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 50, 141, 20))
        self.radioButton_2.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 90, 141, 20))
        self.radioButton_3.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 130, 221, 20))
        self.radioButton_4.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_5.setGeometry(QtCore.QRect(50, 170, 221, 20))
        self.radioButton_5.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_6.setGeometry(QtCore.QRect(50, 210, 161, 20))
        self.radioButton_6.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(350, 20, 141, 20))
        self.label.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(360, 60, 113, 20))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 100, 75, 23))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.315975, y1:1, x2:0.31595, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 140, 51, 20))
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        Metricoscience.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Metricoscience)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Metricoscience.setStatusBar(self.statusbar)
        self.pic = QtGui.QLabel(Metricoscience)
        self.pic.setGeometry(250, 171, 310, 276)
        self.pic.setPixmap(QtGui.QPixmap(r"C:\Users\pc\Desktop\mos.jpg"))
        self.retranslateUi(Metricoscience)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pic.show)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frame_2.show)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pic.close)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frame_2.close)
        
#        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_2.paste)
        QtCore.QMetaObject.connectSlotsByName(Metricoscience)

    def retranslateUi(self, Metricoscience):
        Metricoscience.setWindowTitle(_translate("Metricoscience", "MainWindow", None))
        self.pushButton_4.setText(_translate("Metricoscience", "HOME", None))
        self.pushButton_3.setText(_translate("Metricoscience", "RESEARCH", None))
        self.pushButton_2.setText(_translate("Metricoscience", "STATS", None))
        self.pushButton.setText(_translate("Metricoscience", "ABOUT", None))
        self.radioButton.setText(_translate("Metricoscience", "Nombre de citation", None))
        self.radioButton_2.setText(_translate("Metricoscience", "H_index", None))
        self.radioButton_3.setText(_translate("Metricoscience", "Nombre_de_publication", None))
        self.radioButton_4.setText(_translate("Metricoscience", "Nombre_de_publication_web_of_science", None))
        self.radioButton_5.setText(_translate("Metricoscience", "Nombre_de_publication_scopus", None))
        self.radioButton_6.setText(_translate("Metricoscience", "Nombre_de_publication_IET", None))
        self.label.setText(_translate("Metricoscience", "Donner le Nom du chercheur ", None))
        self.pushButton_5.setText(_translate("Metricoscience", "RESULTAT", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Metricoscience = QtGui.QMainWindow()
    ui = Ui_Metricoscience()
    ui.setupUi(Metricoscience)
    Metricoscience.show()
    sys.exit(app.exec_())

